# Generated by Django 4.2.4 on 2023-08-26 09:49

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to=item.models.Items.upload_to)),
                ('is_available', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('seller', models.TextField(blank=True)),
            ],
        ),
    ]
